[versions]
agp = "9.0.0-beta01"
activity = "1.12.0-rc01"
appcompat = "1.7.1"
commonsCodec = "1.20.0"
constraintlayout = "2.2.1"
material = "1.14.0-alpha06"
securityCrypto = "1.1.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }