[versions]
agp = "9.0.0-beta01"
activity = "1.12.0-rc01"
appcompat = "1.7.1"
commonsCodec = "1.20.0"
constraintlayout = "2.2.1"
material = "1.14.0-alpha06"
okhttp = "5.3.2"
roomRuntime = "2.8.3"
securityCrypto = "1.1.0"
markwon = "4.6.2"
camera = "1.6.0-alpha01"
mlkit = "17.3.0"
guava = "31.0.1-android"
gson = "2.13.2"
zxing = "3.5.4"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
markwon = { module = "io.noties.markwon:core", version.ref = "markwon" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }
mlkit = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }